-- MySQL Script generated by MySQL Workbench
-- Tue Jun 18 19:16:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema envio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema envio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `envio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `envio` ;

-- -----------------------------------------------------
-- Table `envio`.`cameras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `envio`.`cameras` (
  `cameraid` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `MAC` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cameraid`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `envio`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `envio`.`clientes` (
  `clienteid` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `numero_cliente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`clienteid`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `envio`.`envios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `envio`.`envios` (
  `envioid` INT NOT NULL AUTO_INCREMENT,
  `clienteid` INT NULL DEFAULT NULL,
  `cameraid` INT NULL DEFAULT NULL,
  `acesso` VARCHAR(45) NULL DEFAULT NULL,
  `data_entrega` VARCHAR(45) NULL DEFAULT NULL,
  `data_envio` VARCHAR(45) NULL DEFAULT NULL,
  `data_instalacao` VARCHAR(45) NULL DEFAULT NULL,
  `nota_fiscal` INT NULL DEFAULT NULL,
  `sequencia` INT NULL DEFAULT NULL,
  `numero_pedido` INT NULL DEFAULT NULL,
  PRIMARY KEY (`envioid`),
  INDEX `clienteid_idx` (`clienteid` ASC) VISIBLE,
  INDEX `cameraid_idx` (`cameraid` ASC) VISIBLE,
  CONSTRAINT `cameraid`
    FOREIGN KEY (`cameraid`)
    REFERENCES `envio`.`cameras` (`cameraid`),
  CONSTRAINT `clienteid`
    FOREIGN KEY (`clienteid`)
    REFERENCES `envio`.`clientes` (`clienteid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
